[workspace]

# Was necessary after switching to dev tree-sitter to fix this warning:
# > some crates are on edition 2021 which defaults to `resolver = "2"`, but
# > virtual workspaces default to `resolver = "1"`.
#
# Also necessary to enable the `testing` feature of harp only when testing
# (i.e. when building downstream packages like Ark with Harp's `testing`
# feature set in `dev-dependencies`).
resolver = "2"

members = [
    "crates/amalthea",
    "crates/ark",
    "crates/echo",
    "crates/harp",
    "crates/libr",
    "crates/stdext",
]

[workspace.package]
rust-version = "1.89"
edition = "2021"
license = "MIT"
authors = ["Posit Software, PBC"]

[workspace.dependencies]
biome_line_index = { git = "https://github.com/biomejs/biome", rev = "c13fc60726883781e4530a4437724273b560c8e0" }
