[package]
name = "stdext"
version = "0.1.0"
edition = "2021"
rust-version = "1.64.0"
description = """
Useful extensions to the Rust standard library.
"""

[dependencies]
backtrace = "0.3.67"
libc = "0.2.146"
log = "0.4.18"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
