id = "ark-lsp"
name = "Ark R Language Server"
description = "R language support via ark-lsp static analysis"
version = "0.1.0"
schema_version = 1
authors = ["Posit Software, PBC"]
repository = "https://github.com/posit-dev/ark"

[language_servers.ark-lsp]
name = "Ark LSP"
languages = ["R"]
